### ISSUE TITLE
`view.totalPages` becomes `1` when current page is out of bounds

### ISSUE THREAD

**Issue by donaldgray** [dlcs/iiif-presentation#107]
The `totalPages` of a hydra view object would previously always show a number of pages in a collection according to the `pageSize` value. 

It appears that this has changed - if the current page is "out of bounds" (e.g there's 10 pages but the `page` query parameter in the URL is 11) it will be set to 1.

How should this be handled?

Note by @griffri 24/10/2024 - `totalItems` is also set to 0 when the current page is out of bounds.

Note by @griffri 18/11/2024 - Found a related issue - the returned 'totalItems' for a collection will be incorrect if the 'page' query parameter is out of bounds by more than one page.
Take a storage collection containing 16 items for example - the following query parameters cause the expected value to be returned:

- `page=1&pageSize=16`: returns `"totalItems":16` 
- `page=1&pageSize=8`: returns `"totalItems":16` 
- `page=2&pageSize=16`: returns `"totalItems":16` 

But a `page` value larger than 2 will cause `totalItems` to increase beyond the actual size of the collection:

- `page=3&pageSize=16`: returns a `"totalItems":32` 
- `page=4&pageSize=16`: returns a `"totalItems":48` 
- ...etc

Previously these would returned a `totalItems` of 16, but it appears to have changed recently.

**Comment by p-kaczynski** [comment]
Personally I view a request with `page` out of bounds as a `400 Bad Request`. That might be heavy handed, but makes the issue go away, as there would be _no_ response body. For an API user this should be acceptable, for an UI this should not happen in the first place naturally, and is within the UI's wheelhouse to make a correct request instead, e.g. defaulting to `page=1`.
