### ISSUE TITLE
Create job-runner project

### ISSUE THREAD

**Issue by donaldgray** [dlcs/iiif-presentation#172]
This is preparatory work for `paintedResource` handling.

Move the `CustomerCreatedListenerService : BackgroundWorker` from the API project to it's own separate project. This project "job-runner" (name me better) project will hold a couple of listener services, customer-created being the first.

Behaviour should continue to work as-is. 

There will be multiple `BackgroundWorkers` in "job-runner" so have a method to enable/disable based on appSettings.

**Comment by donaldgray** [comment]
The outcome of this ticket is that we will have 2 deployable Docker containers - 1 for the API, 1 for background-processing.

The behaviour of the overall application will remain unchanged.

**Comment by griffri** [comment]
Looks good to me - moving to 'done'.
