### ISSUE TITLE
Manifest create handles `Asset`

### ISSUE THREAD

**Issue by donaldgray** [dlcs/iiif-presentation#173]
Creation only (for now) via PUT or POST. If update attempted on a `Manifest` that has assets - reject (temporary).

Process:
* On receipt on a manifest with `"paintedResource.asset"` property
  * For now - if `"paintedResource"` AND `"items"` provided reject w/ 400.
* Parse the assets to make 1:n DLCS batches
  * Require Manifest has header from #139 for now
* Save `Asset` in `canvasPaintings` table
  * Set defaults for `canvasPaintings` - 1 image per canvas, no choice. Ordered as how assets were provided.
  * When returning `"asset"` property on manifest return the Asset URI _only_
* Post batches to DLCS
* Record BatchId for each manifest
* In S3 save the manifest with no `"items"` property (will be populated when batches complete)
* If an asset specifies `"space"` use it. Else fallback to "space" in Manifest table.

**Comment by donaldgray** [comment]
Requires #139

**Comment by JackLewis-digirati** [comment]
**NOTE:** the `ingesting` property on a manifest should be derived from the asset response from `allImages`
