### ISSUE TITLE
AWS presentation instance returning HTTP URL's

### ISSUE THREAD

**Issue by JackLewis-digirati** [dlcs/iiif-presentation#21]
When returning resources from the AWS instance of the presentation API, URL's are returned with a `http`  schema, instead of `https`.

i.e:

```json
"id": "http://presentation-api.dlcs.digirati.io/1/collections/0909385a-d8bb-4254-b7a5-f3f3a7939c3a"
```

**Comment by donaldgray** [comment]
Note: This is likely due to missing `app.UseForwardedHeaders()` / `services.Configure<ForwardedHeadersOptions>`
