### ISSUE TITLE
use more human readable method of minting identifiers, over GUIDs

### ISSUE THREAD

**Issue by sarahos** [dlcs/iiif-presentation#25]
Protagonist uses a simpler method of generating ID's

- consider Sqids as it's already a NuGet package - https://sqids.org/dotnet
  - Sqids is encoded from numbers, need to look at uniqueness with these numbers
  - use customer id + some other numbers?
  - make sure on second attempt, id is different
- if this won't work, create a NuGet package based on the class
- collisions possible, so need to check for uniqueness
- unit test for checking that duplicate ID's are rejected
- Leeds will use a custom ID retrieved from their system

Acceptance Criteria:
- (more) human readable ID is generated
- The ID must be unique
- There are multiple possible ID systems, so this should use dependency injection

**Comment by griffri** [comment]
@christinemacdonald Apologies -  this looks like something that can be tested so I'll write up a ticket for it soon.
