### ISSUE TITLE
Make storage collection `slug` case insensitive

### ISSUE THREAD

**Issue by griffri** [dlcs/iiif-presentation#29]
Storage collection slugs are currently case sensitive - e.g, you can `POST` two child storage collections with "mycollection" and "myCollection" as slugs, and you'd end up with two different collections, available from `(parent)/mycollection` and `(parent)/myCollection`.

They should be made case insensitive to avoid any potential confusion.

**Acceptance Criteria:**
- 409 Conflict is returned if an attempt is made to create a storage collection using a slug that is already in use, regardless of casing.

**Comment by tomcrane** [comment]
(but they should not be normalised to lower case)

If I create `My-Storage-Collection` is should stay that way
but I still am not allowed to make `my-storage-collection` or `mY-StOrAgE-CoLleCtIoN`
