### ISSUE TITLE
Update storage collection

### ISSUE THREAD

**Issue by sarahos** [dlcs/iiif-presentation#5]
Create an endpoint where authenticated users can update an existing storage collection.

- [x] new PUT endpoint `/{customerId}/collections/{collectionId}` 

- [x] only the following fields can be edited:

    - label (optional)
    - slug, if slug value changed must be unique
    - parent

- [x] update basic data in database
- [x] updates are rejected if

    - [x] "behavior" does not include "storage-collection" (see [iiif-behaviors](https://deploy-preview-3--dlcs-docs.netlify.app/api-doc/iiif#iiif-behaviors))
    - [x] latest eTag is not provided in headers
    - [x] IIIF-CS-Show-Extras header is not "All"
    - [x] user not authenticated

See related API docs - https://deploy-preview-3--dlcs-docs.netlify.app/api-doc/iiif#example-create-a-storage-collection-within-a-storage-collection

**Comment by JackLewis-digirati** [comment]
I think behavior will also be allowed to be edited, as without it we can't check for `"behavior" does not include "storage-collection"`

**Comment by sarahos** [comment]
possible extension to the current behaviour - https://github.com/orgs/dlcs/projects/7/views/1?pane=issue&itemId=80080700
