### ISSUE TITLE
PUT IIIF Collection

### ISSUE THREAD

**Issue by JackLewis-digirati** [dlcs/iiif-presentation#54]
Update existing Create endpoint to support creating IIIF Collections

part 1:

https://deploy-preview-3--dlcs-docs.netlify.app/api-doc/iiif#example-create-a-iiif-collection-within-a-storage-collection

see https://github.com/dlcs/iiif-presentation/issues/28

addition to PUT endpoint /{customer id}/collections/{id}
- IIIF Collections do not contain the "storage-collection" behavior (see [iiif-behaviors](https://deploy-preview-3--dlcs-docs.netlify.app/api-doc/iiif#iiif-behaviors))
- still requires data added to the database but IsStorageCollection = false
- JSON document needs to be saved to S3
- Any valid IIIF collection can be saved
- slug and parent properties are required
- retrieved document should be equivalent to saved
- the ID field should be the same as generated by the ID

**Comment by tomcrane** [comment]
Saves anything in `items` (as JSON in S3) but does not process it.

**Comment by JackLewis-digirati** [comment]
**NOTE:** look into model binding + reading contents separately
