### ISSUE TITLE
Move hierarchy to a separate table

### ISSUE THREAD

**Issue by JackLewis-digirati** [dlcs/iiif-presentation#59]
Maybe consider this before starting on manifests and refactor.
It's simpler for one table when it's just collections (both storage and IIIF colls are the same table), but once we have a hierarchy of mixed colls and manifests, this might be better:

```
create table if not exists public.hierarchy
(
    id                    text,    -- pk in collections OR manifests table
    type                  int,     -- storage coll=0, iiif coll=1, manifest=2
    slug                  text,
    parent                text,
    items_order           int,
    public                boolean,
    canonical             boolean
);
```

slug, parent and items_order would be dropped from the collections table and the manifests table

---

I think that only manifests and collections managed by the platform appear in the manifests and collections tables.
A IIIF Collection we store could reference external manifests and/or collections in the JSON we save for it and that never appears in any of these tables.

For those we do manage, that table is doing multiple jobs:
- resolving incoming hierarchical paths to specific resources (hierarchical query to determine which IIIF thing to load off disk, decorate and serve)
- generating paths to emit in generated id properties we decorate our outgoing JSON with
driving the explorer-style view of your IIIF repository in the portal (which is driven by the API providing navigable collections) - this only shows managed iiif resources; you can only tell that your collection's items property includes a BL manifest by looking that the JSON
- recording membership information, so that you can include a particular managed manifest in multiple places, and see that reflected in the portal UI

I didn't have that canonical property in before.
In this table, id is not always unique.
But for any id, there must be one and only one row for which canonical=true.
Most of the time that means one occurrence of id which therefore must have canonical=true
Where id appears multiple times, the rows that are canonical=false are like symlinks. They appear in the tree as you browse so you can see the membership relationship, but if you navigated into it you'd get to its canonical path.

And we could also use this information to redirect HTTP requests from "symlink" to canonical URLs - although really the non-canonical path shouldn't ever be published anywhere in a IIIF resource

**Comment by tomcrane** [comment]
The problem with this...
...is how does it align with the `slug` and `parent` properties that we post as properties of our manifests and collections?

That table is still incomplete:

```
create table if not exists public.hierarchy
(
    hierarchy_id          int
    resource_id           text,    -- pk in collections OR manifests table
    type                  int,     -- storage coll=0, iiif coll=1, manifest=2
    slug                  text,
    parent                int,     -- ref hierarchy_id
    items_order           int,
    public                boolean,
    canonical             boolean
);
```

**Comment by tomcrane** [comment]
When you send a manifest or collection with slug and parent properties, they can only be the canonical ones.

So how would you record an alternate - a symlink?

**Comment by JackLewis-digirati** [comment]
think there should be index on `slug` and `parent` as this will stop duplicate slugs between `manifests` and `collections`

 `resource_id`, `type` and `slug` should also be an index, but I believe this would be stopped by the `collections` or `manifests` tables directly

Would it make more sense to have direct FK, rather than ID and a type field? This would make it easier to do a `JOIN` if required

**Comment by JackLewis-digirati** [comment]
we use Entity Framework to generate the table, and table inheritance isn't supported (I think it's because of this - https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_table_inheritance), we could  get around this though by modifying the generated EF SQL though

**Comment by JackLewis-digirati** [comment]
Think this table will also require `CustomerId` as a Collection ID is unique within a customer, rather than just unique

**Comment by JackLewis-digirati** [comment]
this table has been updated since this ticket was initally written to be the following:

```
create table if not exists public.hierarchy
(
    hierarchy_id          int,     -- (pk)
    collection_id         text,    -- fk to collections table id
    manifest_id           text,    -- fk to manifest table id
    customer_id           int      -- used as the second half of the fk for the manifests and collection table
    type                  int,     -- storage coll=0, iiif coll=1, manifest=2
    slug                  text,
    parent                int,     -- ref hierarchy_id
    items_order           int,
    public                boolean,
    canonical             boolean
);
```

Additionally, there's a constraint which says that either `collection_id` OR `manifest_id` must be null (but not both)
