### ISSUE TITLE
Edit an external Manifest

### ISSUE THREAD

**Issue by tomcrane** [dlcs/iiif-presentation#63]
- [ ] Any valid IIIF Presentation 3 JSON in the Manifest is preserved
- [ ] Any changes to the JSON of the `items` property is permitted, but...
- [ ] On each save, the canvas_paintings table is updated to reflect the `items` JSON
- [ ] On a flat request for the edited manifest, the `paintedResources` property reflects the change (but still no `asset` property as they aren't our assets yet)

(NB the `items` JSON is never generated by the DLCS, it only reflects it back to the canvas_paintings table)
BUT the `paintedResources` info _is_ generated from that table - so the DB persistence can be tested by looking at the `paintedResources` property.

**Comment by donaldgray** [comment]
Is this still required? Or is it covered by #62 ?

**Comment by sarahos** [comment]
agreed to close as a duplicate of #62
