### ISSUE TITLE
Update FlatCollection to use the iiif-net package

### ISSUE THREAD

**Issue by sarahos** [dlcs/iiif-presentation#7]
This ticket will not contain changes for playwright testing and is more of a tech task

FlatCollection is used to show additional properties to a standard IIIF collection, it would make sense to use inheritance from the centralized iiif-net library collections.  This was attempted earlier, but failed due to issues with serialization

see:
https://github.com/digirati-co-uk/iiif-net
https://github.com/dlcs/iiif-presentation/blob/feature/updateCollection/src/IIIFPresentation/Models/API/Collection/FlatCollection.cs

- rename `FlatCollection` to `PresentationCollection`
- investigate using inheritance between `Collection` and `FlatCollection`
- Possible fix: allow custom serializers in the iiif-net library

**Comment by donaldgray** [comment]
Moving to 'done' as no specific tests required for this.
