### ISSUE TITLE
Add authentication to the API

### ISSUE THREAD

**Issue by tomcrane** [dlcs/iiif-presentation#89]
For MVP in **iiif-presentation** application this can just be a delegated auth handler - 

 - [ ] detect basic HTTP auth credentials in request
 - [ ] use these to make HTTP request to "legacy" DLCS API for Customer
 - [ ] if 200 OK, cache the credentials in memory cache in iiif-presentation app
 - [ ] on subsequent requests, authenticate the users creds against the memory cache
 
(THIS IS NOT PRODUCTION!)

**Comment by donaldgray** [comment]
Note that this request slightly changes behaviour. Until now, failing to provide auth header _or_ `x-iiif-cs` header would return in a 403 but, depending on the scenario, you can get a 401 or 403
