### ISSUE TITLE
Rename IIIF-CS-Show-Extra header

### ISSUE THREAD

**Issue by sarahos** [dlcs/iiif-presentation#9]
In order to retrieve extra information from the API, a header of `IIIF-CS-Show-Extras` with the value of `All`.  

There's a possible requirement to show domain specific headers with the prefix of `X-`, so this header should be `X-IIIF-CS-Show-Extras`

**NOTE:** This should be checked by the product owner before implementation

**Comment by donaldgray** [comment]
The currently handled header is `IIIF-CS-Show-Extra` but it should be `X-IIIF-CS-Show-Extras` or `IIIF-CS-Show-Extras` (`Extras` plural, rather than `Extra`) depending on decision.

**Comment by JackLewis-digirati** [comment]
Spoke with Tom about this, decision is to use `X-IIIF-CS-Show-Extras`
