### ISSUE TITLE
POST to create iiif-collection incorrectly stores JSON

### ISSUE THREAD

**Issue by donaldgray** [dlcs/iiif-presentation#99]
POSTing to create a iiif-collection results in the S3 object being stored with `PascalCase` properties, rather than `camelCase`.

When requesting the properties are returned as such.

Stored object should not have the `public-iiif` behaviour returned for hierarchical path as this would require the additional, custom context to be returned.

**Comment by griffri** [comment]
JSON stored in S3 and returned from Presentation are in `camelCase`.
